name: flutter_bloc_task_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  bloc: ^8.1.1
  build_runner: ^2.3.3
  collection: ^1.17.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  intl: ^0.18.0
  path_provider: ^2.0.13
  snackbar: ^1.0.2
  step_progress_indicator: ^1.0.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.1

flutter:
  uses-material-design: true
